name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "bugfix"
      - "fix"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
    collapse-after: 5
  - title: "🏠 HA Integration"
    labels:
      - "ha-integration"
  - title: "🔧 Internal / CI"
    labels:
      - "ci"
      - "internal"
    collapse-after: 3

  - title: "🔀 Other"
    labels: []

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "ci"
    files:
      - ".github/**"
      - "pyproject.toml"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - ".vscode/**"
    title:
      - "/^ci:/i"

  - label: "dependencies"
    title:
      - "/^(chore|build)\\(deps\\)/i"
      - "/^bump /i"

  - label: "bug"
    title:
      - "/^fix[:(]/i"

  - label: "enhancement"
    title:
      - "/^feat[:(]/i"

template: |
  ## What's changed
  $CHANGES

  **Full changelog:** $PREVIOUS_TAG...v$NEXT_PATCH_VERSION
