"""evohomeasync provides an async client for the Resideo TCC API."""

from __future__ import annotations

try:
    # generated by hatch-vcs at build time, but for dev/test, run: pip install -e .
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0"

__all__ = ["__version__"]
