name: Tag


on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"
      - "[0-9]*.[0-9]*.[0-9]*"  # invalid, trigger on these to provide feedback


permissions:
  contents: read


jobs:
  validate-tag:  # Don't go any further, if there is no valid tag
    name: Validate tag
    uses: ./.github/workflows/check-tag.yml
    with:
      tag_name: ${{ github.ref_name }}

  check-lint:
    name: Linting
    needs: [validate-tag]
    uses: ./.github/workflows/check-lint.yml

  check-type:
    name: Typing
    needs: [validate-tag]
    uses: ./.github/workflows/check-type.yml

  check-tests:
    name: Testing
    needs: [validate-tag]
    uses: ./.github/workflows/check-tests.yml

  ha-integration-stable:
    name: HA Integration (stable)
    needs: [check-lint, check-type, check-tests]
    uses: ./.github/workflows/check-hass-tests.yml
    with:
      ha_version: "master"
